'use strict';

// Everything that writes public HTML.
//
// The one rule that shapes this file: a generated post page must be indistinguishable
// from a hand-written one, and CI's `stylesheets-identical` rule fails the build if it is
// not. So the stylesheet and the masthead are not copied into this file — they are LIFTED
// OUT OF `blog.html` at publish time and re-emitted verbatim, with relative paths rewritten
// for the one-directory-deeper location. A post can therefore never drift from the site's
// style, and a future edit to the shared sheet reaches new posts with no second edit here.
// (Existing post pages are regenerated by re-saving them; that is the same three-way edit
// AGENTS.md already describes, one file wider.)

const { escapeHtml, renderMarkdown } = require('./markdown');
const { displayDate, publicUrl } = require('./posts');

const SITE = 'https://jonathangong.com';

// The clause `blog.html`'s three description tags carry while the blog is empty. It is
// removed when the first post lands and restored when the last one goes, so the page never
// claims to have no posts while listing some.
const EMPTY_CLAUSE = ' No posts yet; the first is being written.';

const DEFAULT_NOTE =
  'Notes on what I&rsquo;m building, mostly about AI systems and the people who use them.';

// JSON that is safe inside a `<script>` element, which is not the same thing as valid
// JSON. An HTML parser ends the element at the first `</script`, whatever the JSON quoting
// around it, so a title that merely mentions one would truncate this block and drop the
// rest of the post's metadata into the page as live markup — the one place in this file
// where author text would reach the output without going through `escapeHtml`. U+2028 and
// U+2029 are escaped for the same reason from the other side: JSON allows them raw and
// JavaScript reads them as line terminators.
function jsonForScript(value) {
  return JSON.stringify(value)
    .replace(/&/g, '\\u0026')
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function extractBlock(html, tag) {
  const match = html.match(new RegExp(`<${tag}[^>]*>[\\s\\S]*?</${tag}>`, 'i'));
  return match ? match[0] : null;
}

// A post page sits one directory down, so every relative URL in the lifted masthead gains
// a `../`. Absolute URLs, fragments, root-relative paths, and `mailto:` are left alone.
function reparent(html) {
  return html.replace(/\b(href|src)="([^"]*)"/gi, (match, attribute, url) => {
    if (!url || /^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(url)) return match;
    return `${attribute}="../${url}"`;
  });
}

/**
 * A complete standalone post page, built from the live `blog.html`.
 *
 * Throws if `blog.html` has no `<style>` or `<header>` to lift — better to refuse to
 * publish than to ship a page that fails the design rules.
 */
function postPage(post, blogHtml) {
  const style = extractBlock(blogHtml, 'style');
  const header = extractBlock(blogHtml, 'header');
  if (!style || !header) {
    throw new Error('blog.html is missing its <style> or <header> block');
  }

  const title = escapeHtml(post.title);
  const summary = escapeHtml(post.summary);
  const url = publicUrl(post.slug);
  const pageTitle = `${title} &mdash; Jonathan Gong`;
  const plainTitle = title;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${pageTitle}</title>
<meta name="description" content="${summary}">
<meta name="author" content="Jonathan Gong">
<link rel="canonical" href="${url}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Jonathan Gong">
<meta property="og:title" content="${plainTitle}">
<meta property="og:description" content="${summary}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${SITE}/headshot.jpg">
<meta property="og:image:alt" content="Jonathan Gong">
<meta property="article:published_time" content="${escapeHtml(post.date)}">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="${plainTitle}">
<meta name="twitter:description" content="${summary}">
<meta name="twitter:image" content="${SITE}/headshot.jpg">
<link rel="icon" href="../favicon.ico" sizes="any">
<link rel="apple-touch-icon" href="../apple-touch-icon.png">
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": ${jsonForScript(post.title)},
  "description": ${jsonForScript(post.summary)},
  "datePublished": ${jsonForScript(post.date)},
  "url": ${jsonForScript(url)},
  "image": "${SITE}/headshot.jpg",
  "author": {
    "@type": "Person",
    "name": "Jonathan Gong",
    "url": "${SITE}/"
  }
}
</script>
${style}
</head>
<body>
<div class="page">

  ${reparent(header)}

  <main>
    <article>
      <h1 class="post-title">${plainTitle}</h1>
      <p class="post-meta">${escapeHtml(displayDate(post.date))}</p>
      <div class="post-body">
${renderMarkdown(post.markdown)}
      </div>
    </article>
    <p class="post-back"><a href="../blog.html">All posts</a></p>
  </main>

</div>
</body>
</html>
`;
}

/**
 * `blog.html` with its `<main>` and description tags rewritten for the given posts.
 *
 * With no posts the output is byte-identical to the placeholder the page ships with, so
 * deleting the last post restores the page exactly rather than leaving an empty shell.
 * The `.note` line's own text is preserved from whatever is on the page — only the space
 * above it changes, because 24px reads as a footnote to the placeholder sentence and as a
 * crowding of the last post once there are posts.
 */
function blogIndex(blogHtml, posts) {
  const noteMatch = blogHtml.match(/<p class="note"[^>]*>([\s\S]*?)<\/p>/i);
  const note = noteMatch ? noteMatch[1] : DEFAULT_NOTE;

  let main;
  if (posts.length === 0) {
    main = `  <main>
    <p>No posts yet. The first one is being written.</p>
    <p class="note" style="margin-top:24px">${note}</p>

  </main>`;
  } else {
    const entries = posts.map((post) => `      <article class="entry">
        <p class="entry-title"><a href="blog/${post.slug}.html">${escapeHtml(post.title)}</a></p>
        <p class="entry-meta">${escapeHtml(displayDate(post.date))}</p>
        <p class="entry-body">${escapeHtml(post.summary)}</p>
      </article>`).join('\n\n');
    main = `  <main>
    <div class="posts">

${entries}

    </div>
    <p class="note" style="margin-top:56px">${note}</p>

  </main>`;
  }

  // A publish that quietly failed to find `<main>` would commit an index still showing
  // "No posts yet" beside a live post page, and `posts-listed` would only catch it after
  // the fact. Refusing to publish is the better failure.
  const MAIN = / {2}<main>[\s\S]*?<\/main>/;
  if (!MAIN.test(blogHtml)) {
    throw new Error('blog.html has no <main> block to rewrite');
  }
  let out = blogHtml.replace(MAIN, () => main);

  // The three description tags claim an empty blog. Add or remove that claim to match.
  if (posts.length === 0) {
    if (!out.includes(EMPTY_CLAUSE)) {
      out = out.replace(/(have to use them\.)(")/g, `$1${EMPTY_CLAUSE}$2`);
    }
  } else {
    out = out.split(EMPTY_CLAUSE).join('');
  }
  return out;
}

// The comment deliberately does not name the admin path. `sitemap.xml` is fetched by
// every crawler and scraper that visits, and there is no reason to hand them the URL of
// the one page on this site that must never be found.
const SITEMAP_MARKER = '  <!-- Blog posts, newest first. This block is rewritten whenever a post is\n'
  + '       published, unpublished, or deleted; it is not maintained by hand. -->';

/**
 * `sitemap.xml` with the published posts listed after the two hand-written entries.
 *
 * The block is rebuilt whole from a marker comment to `</urlset>`, so publishing,
 * unpublishing, and deleting all converge on the same file rather than accumulating
 * stale entries.
 */
function sitemap(currentXml, posts) {
  const markerAt = currentXml.indexOf('  <!-- Blog posts,');
  const closeAt = currentXml.lastIndexOf('</urlset>');
  const head = (markerAt >= 0 ? currentXml.slice(0, markerAt) : currentXml.slice(0, closeAt)).replace(/\s*$/, '\n');

  if (posts.length === 0) return `${head}</urlset>\n`;

  const entries = posts.map((post) => `  <url>
    <loc>${escapeHtml(publicUrl(post.slug))}</loc>
    <lastmod>${escapeHtml(post.date)}</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>`).join('\n');

  return `${head}${SITEMAP_MARKER}\n${entries}\n</urlset>\n`;
}

module.exports = { EMPTY_CLAUSE, postPage, blogIndex, sitemap, reparent, extractBlock, jsonForScript };
